### ISSUE TITLE
Integration of Pubble

### ISSUE THREAD

**Issue by ghost** [fablaborg/demo#5] opened 2017-07-18 13:02 UTC
I run a pubble account on the current fablab.org site where I occasionally get requests and give answers pointing people to labs, sites, making connections etc.
I would want to maintain that. This requires including the below code on the page:
`

<div class="pubble-app" data-app-id="11777" data-app-identifier="11777"></div>
<script type="text/javascript" src="https://cdn.pubble.io/javascript/loader.js" defer></script>

`

**Comment by openp2pdesign** [comment] 2017-07-19 16:04
This is basically a duplicate of #4, the Discourse integration should be the main discussion channel regarding this topic. I close the issue now, we should test the Discourse integration for few months at least before considering changes in the communication channels for fablab.org, but it should be just one channel.

**Closed as completed by openp2pdesign** 2017-07-19 16:04 UTC

**Comment by ghost** [comment] 2017-07-19 18:49
Don't agree. Pubble is more like a helpdesk, not the discussion about what should and should not be on the landing page for which we added the discuss widget.

**Comment by openp2pdesign** [comment] 2017-07-28 07:10
Yes, it's something different, but then we should discuss it on the Discourse thread about this page (otherwise here it's just you and me... and let's keep here just the technical discussion). I'd keep a system similar to Fablabs.io, where the helpdesk is only for technical issues and every other discussion is on Discourse, but then for a static site the helpdesk is an overkill. Let's discuss this [in the Discourse thread](http://discuss.fablabs.io/t/curating-fablab-org/4186/2).
